logo = "/uploads/pcideaz-logo.png"
icon = "/uploads/pcideaz-favicon.jpg"
tagline = "Provides helpful knowledge for audience"
contacteMail = "zohaibhxn@gmail.com"
G4analytics = "UA-229521957-1"
img_section = []

[colors]
bodyBG = ""
sectionBG = ""

[amznTracking]
global = ""
topProducts = ""
table = ""
review = ""

[open_graph]
meta_Description = ""
image = "/images/logo.png"

[verifications]
googleSiteVerify = ""
BingWebmaster = ""
PinterestVerify = ""

[social_accounts]
sitefbAccount = "https://facebook.com/"
sitetwitterAccount = "https://twitter.com/"
siteinstagramAccount = "https://instagram.com/"
sitepinterestAccount = "https://pinterest.com/"
siteYouTubeAccount = "https://youtube.com/"

[[scroll_section]]
scrollcat = "Motherboards"

[[scroll_section]]
scrollcat = "Graphics Cards"

[[scroll_section]]
scrollcat = "RAMs"

[post_setting]
featured_img = true
show_comments = false

[home_setting]
footerText = ""
headerText = ""
blogSection = false
headerStyle = "Style 2"