logo = "/images/logo.png"
icon = "/images/favicon.png"
tagline = "Provides helpful knowledge for audience"
contacteMail = "zohaibhxn@gmail.com"
G4analytics = "UA-229521957-1"
img_section = []

[colors]
bodyBG = ""
sectionBG = ""

[amznTracking]
global = "salesmag-20"
topProducts = "salesmagtable-20"
table = "salesmagtable-20"
review = "salesmagreview-20"

[open_graph]
meta_Description = "If you're looking to create a professional website that will help you increase your affiliate sales, look no further than this Netlify theme."
image = "/images/logo.png"

[verifications]
googleSiteVerify = ""
BingWebmaster = ""
PinterestVerify = ""

[social_accounts]
sitefbAccount = "https://facebook.com/"
sitetwitterAccount = "https://twitter.com/"
siteinstagramAccount = "https://instagram.com/"
sitepinterestAccount = "https://pinterest.com/"
siteYouTubeAccount = "https://youtube.com/"

[[scroll_section]]
scrollcat = "Motherboards"

[[scroll_section]]
scrollcat = "Graphics Cards"

[[scroll_section]]
scrollcat = "RAMs"

[post_setting]
featured_img = true
show_comments = false

[home_setting]
footerText = ""
headerText = ""
blogSection = false
headerStyle = "Style 2"